version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "montly"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - no-changelog-entry-needed
