# Arrays create problems with old toml, so include them for testing
[dependency-groups]
dev = ["pip", {include-group = "doc"}]
doc = ["sphinx"]

[tool.towncrier]
directory = "changes/"

[tool.changelog-bot]

[tool.changelog-bot.towncrier_changelog]
enabled = true
verify_pr_number = true
