# Arrays create problems with old toml, so include them for testing
[dependency-groups]
dev = ["pip", {include-group = "doc"}]
doc = ["sphinx"]

[tool.towncrier]
filename = "CHANGES.rst"
directory = "changes/"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "New Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "api"
        name = "API Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug Fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Other Changes and Additions"
        showcontent = true

[tool.changelog-bot]

[tool.changelog-bot.towncrier_changelog]
changelog_skip_label = "no-changelog-entry-needed"
enabled = true
verify_pr_number = true
