# Arrays create problems with old toml, so include them for testing
[dependency-groups]
dev = ["pip", {include-group = "doc"}]
doc = ["sphinx"]

[tool.towncrier]
directory = "test_data/changes/dev/"
filename = "test_data/changes/dev.rst"
