# Arrays create problems with old toml, so include them for testing
[dependency-groups]
dev = ["pip", {include-group = "doc"}]
doc = ["sphinx"]

[tool.towncrier]
directory = "test_data/changes/dev/"
filename = "test_data/changes/dev.rst"
issue_format = "`#{issue} <https://github.com/mne-tools/mne-python/pull/{issue}>`__"
package = "mne"
title_format = "{version} ({project_date})"

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true
